### ISSUE TITLE
Office Fabric for Xamarin Forms 

### ISSUE THREAD

**Issue by heavenwing** [OfficeDev/Office-UI-Fabric-iOS#9]
Any plan for Office Fabric for Xamarin Forms ?

**Comment by mikewheaton** [comment]
We don't have any plans at this time. However, we're always happy to see open source implementations like the [Angular version of Fabric](http://ngofficeuifabric.com/). So if you're interested in starting this, please let us know how we might be able to help.

**Comment by heavenwing** [comment]
@mike 
Thanks for you reply. Can we create Xamarin Forms version with binding to iOS version?

**Comment by mikewheaton** [comment]
I'm not familiar with Xamarin Forms myself, so am not sure if that's possible or not. If it is and you want to release an open-source library that does that, please let us know.
